name: Release

# Releasesへのファイル追加のために書き込み権限が必要
permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  # Add a job that depends on the testing workflow
  Test:
    uses: ./.github/workflows/testing.yml


  build:
    needs: [Test]  # Wait for the tests to succeed
    runs-on: ${{ matrix.job.runner }}
    strategy:
      fail-fast: false
      matrix:
        job:
            - target: x86_64-unknown-linux-gnu
              extension: ""
              runner: ubuntu-latest
              cross: true
            - target: x86_64-pc-windows-msvc
              extension: ".exe"
              runner: windows-latest
              cross: false
            - target: x86_64-apple-darwin
              extension: ""
              runner: macos-latest
              cross: false
            - target: aarch64-unknown-linux-gnu
              extension: ""
              runner: ubuntu-latest
              cross: true
            - target: aarch64-pc-windows-msvc
              extension: ".exe"
              runner: windows-latest
              cross: false
            - target: aarch64-apple-darwin
              extension: ""
              runner: macos-latest
              cross: false
            - target: armv7-unknown-linux-gnueabihf
              extension: ""
              runner: ubuntu-latest
              cross: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Get the package name from Cargo.toml and set it as an environment variablea
      - name: Extract crate information
        shell: bash
        run: |
          echo "PROJECT_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> $GITHUB_ENV
          
      # Install Cross
      - name: Install cross
        if: ${{ matrix.job.cross }}
        run: cargo install cross --git https://github.com/cross-rs/cross
        
      # Build the project
      - name: Build by cross
        if: ${{ matrix.job.cross }}
        run: cross build --release --target ${{ matrix.job.target }} --verbose
        
      # Install Target
      - name: Install target
        if: ${{ !matrix.job.cross }}
        run: rustup target add ${{ matrix.job.target }}
      # Build the project without cross
      - name: Build
        if: ${{ !matrix.job.cross }}
        run: cargo build --release --target ${{ matrix.job.target }} --verbose

      # ビルド済みバイナリをリネーム
      - name: Rename artifacts
        shell: bash
        run: |
          mv target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }}{,-${{ github.ref_name }}-${{ matrix.job.target_name }}${{ matrix.job.extension }}}

      # ビルド済みバイナリをReleasesに配置
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }}-${{ github.ref_name }}-${{ matrix.job.target }}${{ matrix.job.extension }}
