name: Release

# Releasesへのファイル追加のために書き込み権限が必要
permissions:
  contents: write

on:
  push:
    tags:
      - v*

jobs:
  # Add a job that depends on the testing workflow
  Test:
    uses: ./.github/workflows/testing.yml


  build:
    needs: [Test]  # Wait for the tests to succeed
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
            - {"target": "x86_64-unknown-linux-gnu:centos", "extension": "", "target_name": "x86_64-unknown-linux-gnu:centos"}
            - {"target": "x86_64-apple-darwin", "extension": "", "target_name": "x86_64-apple-darwin"}
            - {"target": "x86_64-pc-windows-msvc", "extension": ".exe", "target_name": "x86_64-pc-windows-msvc"}
            - {"target": "aarch64-apple-darwin", "extension": "", "target_name": "aarch64-apple-darwin"}
            - {"target": "aarch64-unknown-linux-gnu:centos", "extension": "", "target_name": "aarch64-unknown-linux-gnu:centos"}
            - {"target": "armv7-unknown-linux-gnueabihf", "extension": "", "target_name": "armv7-unknown-linux-gnueabihf"}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Get the package name from Cargo.toml and set it as an environment variablea
      - name: Extract crate information
        shell: bash
        run: |
          echo "PROJECT_NAME=$(sed -n 's/^name = "\(.*\)"/\1/p' Cargo.toml | head -n1)" >> $GITHUB_ENV
          
      # Install Cross
      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
        
      # Build the project
      - name: Build
        run: cross build --release --target ${{ matrix.job.target }} --verbose

      # ビルド済みバイナリをリネーム
      - name: Rename artifacts
        shell: bash
        run: |
          mv target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }}{,-${{ github.ref_name }}-${{ matrix.job.target_name }}${{ matrix.job.extension }}}

      # ビルド済みバイナリをReleasesに配置
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            target/${{ matrix.job.target }}/release/${{ env.PROJECT_NAME }}-${{ github.ref_name }}-${{ matrix.job.target_name }}${{ matrix.job.extension }}
