name: Rust Testing

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ v*.*.* ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    needs: ["check"]
    steps:
      - name: Preparing test
        run: "apt-get update && apt-get install ssh adduser sed python3 -y && sed -i 's/^Port 2222$/Port 22/' /etc/ssh/sshd_config && service ssh start && service ssh reload && useradd -m test && printf \'password\\npassword\\n\' | passwd test"
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Test Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

  check:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt
      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings